name: Bicep Deploy

on:
  workflow_dispatch:

jobs:
  bicepDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CLIENTID }}
          password: ${{ secrets.CLIENTSECRET }}
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
          resourceGroupName: ${{ env.RESOURCEGROUPNAME }}
          template: './InfrastructureAsCode/main.bicep'
          failOnStdErr: false